### ISSUE TITLE
Error without a message

### ISSUE THREAD

**Issue by SaadArdati** [sapher/youtubedl-java#14]
```
com.sapher.youtubedl.YoutubeDLException: 
        at com.sapher.youtubedl.YoutubeDL.execute(YoutubeDL.java:90)
        at <..>.Controller.lambda$request$0(Controller.java:55)
        at java.lang.Thread.run(Thread.java:748)
```

The code:
```java
					File bin = new File("bin/youtube-dl.exe");
					YoutubeDL.setExecutablePath(bin.getAbsolutePath());
					YoutubeDLRequest request = new YoutubeDLRequest(url, downloadDir.getPath());
					request.setOption("format", "bestaudio");
					request.setOption("output", uuid + ".%(ext)s");

					YoutubeDLResponse response = YoutubeDL.execute(request);
					String stdOut = response.getOut();
					System.out.println(stdOut);
```

The error is on the YoutubeDL.execute line.

The code works perfectly on my pc but it errors with the no-message error when I move the jar to my VPS.

**Comment by SaadArdati** [comment]
Updated to the latest commit:

```
startup-script: INFO startup-script: com.sapher.youtubedl.YoutubeDLException: /home/<...>/bin/youtube-dl.exe: 1: /home/<...>/bin/youtube-dl.exe: MZÿÿ¸@è  º´: not found
startup-script: INFO startup-script: /home/<...>/bin/youtube-dl.exe: 2: /home/<...>/bin/youtube-dl.exe: $×}¶HÅ¶HÅ¶HÞ+HÇ¶HÞ+HÄ¶HÞ+¸HÇ¶HÌÎHÂ¶HÅ¶H¶ HÞ+¹Hß¶HÞ+HÄ¶HÞ+HÄ¶HÞ+HÄ¶HRichÅ¶HPELOzFTà
     : not found
startup-script: INFO startup-script: /home/<...>/bin/youtube-dl.exe: 3: /home/<...>/bin/youtube-dl.exe: Syntax error: ")" unexpected
startup-script: INFO startup-script:    at com.sapher.youtubedl.YoutubeDL.execute(YoutubeDL.java:104)
startup-script: INFO startup-script:    at me.<...>.ballerina.Controller.lambda$request$1(Controller.java:52)
startup-script: INFO startup-script:    at java.lang.Thread.run(Thread.java:748)
```
